version: "3"
services:
  frontend:
    image: "${WEBAPP_IMAGE}"
    ports:
      - "80:80"
    restart: always
  backend:
    image: "${API_IMAGE}"
    ports:
      - "9000:9000"
    restart: always
  db:
    image: "${DB_IMAGE}"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
